// A list of all actions in the system.
import { createTypes } from 'reduxsauce'

export default createTypes(`
  LOGIN_ATTEMPT
  LOGIN_SUCCESS
  LOGIN_FAILURE

  LOGOUT

  STARTUP

  TEMPERATURE_REQUEST
  TEMPERATURE_RECEIVE
  TEMPERATURE_FAILURE

  PRODUCTS_REQUEST
  PRODUCTS_RECEIVE
  PRODUCTS_FAILURE

  CATEGORIES_REQUEST
  CATEGORIES_RECEIVE
  CATEGORIES_FAILURE
`)
